[project]
name = "anki-bulgarian-tts"
version = "0.1.0"
description = "Generate TTS audio for Bulgarian text in Anki cards using ElevenLabs"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "requests>=2.28.0",
    "python-dotenv>=1.0.0",
    "elevenlabs>=1.0.0",
]
